### ISSUE TITLE
How to use apitoken in datasource yaml file?

### ISSUE THREAD

**Issue by robinpecha** [grafana/grafana-zabbix#1949]
**Describe the bug**
I can't find any documentation on how to set up authentication to zabbix using the api token in the yaml datasource.

**Expected behavior**
Set api token and authenticate as with username/password.

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 10.4.3  | 6.0.8 | 4.6.1 |

**Description**
From version [4.4.0] - 2023-08-17 is implemented this feature:
Able to use API tokens for authentication, [#1513](https://github.com/alexanderzobnin/grafana-zabbix/issues/1513)
https://github.com/grafana/grafana-zabbix/blob/0355f40fc22fc0e7cb82fced61a9487745c7e640/CHANGELOG.md?plain=1#L124

So Im able to set it via the grafana web ui. But Im failing to do it via datasource yaml file. I cannot find any documentation about this.
So only thing I found is this commit: https://github.com/grafana/grafana-zabbix/pull/1655/commits/ab528e23247716abe8c942264502ba44f79e680e wh and there I found in src/datasource/type.ts value **apitoken**:
![Image](https://github.com/user-attachments/assets/a3a63bb6-3587-429c-bbaa-232c548bccd5)

Please do you have some advice?

This is not working:
```
apiVersion: 1
datasources:
  - name: Zabbix
    type: alexanderzobnin-zabbix-datasource
    url: https://myzabbix.url/api_jsonrpc.php
    access: proxy
    jsonData:
      apitoken: 123456789abcdefghij
    secureJsonData:
      apitoken: 123456789abcdefghij
```

But this works well on the same server:
```
apiVersion: 1
datasources:
  - name: Zabbix
    type: alexanderzobnin-zabbix-datasource
    url: https://myzabbix.url/api_jsonrpc.php
    access: proxy
    jsonData:
      username: myuser
    secureJsonData:
      password: mypassword
```
